import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'

/**
 * PayGate Callback Endpoint
 * 
 * PayGate will call this endpoint when a payment status changes.
 * 
 * Expected parameters from PayGate:
 * - tx_reference: Unique identifier generated by PayGate
 * - identifier: Our internal transaction ID
 * - payment_reference: Payment reference code from Flooz/TMoney
 * - amount: Amount paid by customer
 * - datetime: Payment date and time
 * - payment_method: FLOOZ or TMONEY
 * - phone_number: Customer's phone number
 * - status: Payment status (0=success, 2=pending, 4=expired, 6=cancelled)
 */
export async function POST(request: NextRequest) {
  const requestId = `CB-${Date.now()}`
  console.log(`\n${'='.repeat(60)}`)
  console.log(`🔔 [${requestId}] PayGate Callback - START`)
  console.log(`${'='.repeat(60)}`)

  try {
    // Parse the callback data
    const contentType = request.headers.get('content-type') || ''
    let data: Record<string, string | number> = {}

    if (contentType.includes('application/json')) {
      data = await request.json()
    } else {
      const formData = await request.formData()
      formData.forEach((value, key) => {
        data[key] = value.toString()
      })
    }

    console.log(`📋 [${requestId}] Callback data received:`, JSON.stringify(data, null, 2))

    const { 
      tx_reference, 
      identifier, 
      payment_reference,
      amount,
      datetime,
      payment_method,
      phone_number,
      status 
    } = data

    // Find the payment record
    const payment = await db.payment.findFirst({
      where: {
        OR: [
          { transactionId: identifier as string },
          { paymentToken: tx_reference as string }
        ]
      },
      include: { order: true }
    })

    if (!payment) {
      console.log(`❌ [${requestId}] Payment not found for identifier: ${identifier || tx_reference}`)
      return NextResponse.json({ error: 'Payment not found' }, { status: 404 })
    }

    console.log(`✅ [${requestId}] Found payment: ${payment.id}`)
    console.log(`   Order: ${payment.order.orderNumber}`)

    // Payment status codes from PayGate:
    // 0 = Payment successful
    // 2 = Pending/In progress
    // 4 = Expired
    // 6 = Cancelled

    let newStatus = 'pending'
    let orderStatus = payment.order.status

    if (status === 0) {
      newStatus = 'completed'
      orderStatus = 'paid'
      console.log(`✅ [${requestId}] Payment CONFIRMED!`)
    } else if (status === 2) {
      newStatus = 'pending'
      console.log(`⏳ [${requestId}] Payment PENDING`)
    } else if (status === 4) {
      newStatus = 'expired'
      console.log(`⏰ [${requestId}] Payment EXPIRED`)
    } else if (status === 6) {
      newStatus = 'cancelled'
      console.log(`❌ [${requestId}] Payment CANCELLED`)
    }

    // Update payment record
    await db.payment.update({
      where: { id: payment.id },
      data: {
        status: newStatus,
        paymentToken: tx_reference as string,
        paidAt: status === 0 ? new Date() : null,
        metadata: JSON.stringify({
          ...data,
          callback_received_at: new Date().toISOString()
        })
      }
    })

    console.log(`📝 [${requestId}] Updated payment status to: ${newStatus}`)

    // Update order if payment successful
    if (status === 0) {
      await db.order.update({
        where: { id: payment.orderId },
        data: {
          paymentStatus: 'paid',
          status: 'paid'
        }
      })

      console.log(`✅ [${requestId}] Order ${payment.order.orderNumber} marked as PAID`)
      console.log(`   Payment Reference: ${payment_reference}`)
      console.log(`   Amount: ${amount} FCFA`)
      console.log(`   Phone: ${phone_number}`)
      console.log(`   Method: ${payment_method}`)
    }

    console.log(`${'='.repeat(60)}\n`)

    // Return success to PayGate (always 200 to prevent retries)
    return NextResponse.json({ 
      received: true,
      status: newStatus,
      orderNumber: payment.order.orderNumber
    })

  } catch (error) {
    console.error(`❌ [${requestId}] Callback error:`, error)
    console.log(`${'='.repeat(60)}\n`)
    
    // Still return 200 to prevent PayGate from retrying
    return NextResponse.json({ 
      received: true,
      error: 'Internal error but acknowledged'
    })
  }
}

// GET - For testing callback endpoint
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  const test = searchParams.get('test')

  if (test === 'ping') {
    return NextResponse.json({ 
      status: 'ok', 
      message: 'PayGate callback endpoint is active',
      timestamp: new Date().toISOString(),
      expectedFields: [
        'tx_reference',
        'identifier', 
        'payment_reference',
        'amount',
        'datetime',
        'payment_method',
        'phone_number',
        'status'
      ]
    })
  }

  return NextResponse.json({ 
    endpoint: 'PayGate Callback',
    description: 'This endpoint receives payment notifications from PayGate',
    methods: ['POST'],
    statusCodes: {
      0: 'Payment successful',
      2: 'Pending/In progress', 
      4: 'Expired',
      6: 'Cancelled'
    }
  })
}
